# Generated by Django 5.2.3 on 2025-07-12 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter your full name as it appears on your ID.', max_length=255),
            preserve_default=False,
        ),
    ]
