# Generated by Django 5.2.3 on 2025-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
