# Generated by Django 5.2.3 on 2025-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
