# Generated by Django 5.2.3 on 2025-07-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0008_transcriptrequesttimeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptrequest',
            name='payment_method',
        ),
    ]
